# Generated by Django 2.0 on 2018-04-08 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataFile', models.FileField(blank=True, upload_to='uploads/')),
                ('IDCPostion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.IDCPostion')),
                ('userAdmins', models.ManyToManyField(to='inspection.userAdmin')),
            ],
        ),
    ]
