# Generated by Django 2.0 on 2018-04-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPostPlus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataFile', models.FileField(blank=True, upload_to='uploads/')),
            ],
        ),
    ]
