# Generated by Django 2.0 on 2017-12-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='imageOne',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='imageThree',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='imageTwo',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
