# Generated by Django 2.0 on 2017-12-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_auto_20171221_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='imageOne',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='imageThree',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='imageTwo',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
