# Generated by Django 2.0 on 2018-01-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_auto_20171221_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reportUserInfo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
