# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('serialNumber', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('rackPostion', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventDate', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('imageOne', models.ImageField(upload_to='')),
                ('imageTwo', models.ImageField(upload_to='')),
                ('imageThree', models.ImageField(upload_to='')),
                ('Device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Device')),
            ],
        ),
        migrations.CreateModel(
            name='IDCPostion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDCPostionName', models.CharField(max_length=20)),
                ('TelephoneNumber', models.CharField(max_length=12)),
                ('IDCPostionAddress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_test', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='userAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Depertment', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('TelephoneNumber', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='IDCPostion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.IDCPostion'),
        ),
        migrations.AddField(
            model_name='device',
            name='userAdmins',
            field=models.ManyToManyField(to='polls.userAdmin'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
