# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradmin',
            name='Name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
