# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_useradmin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradmin',
            name='Name',
            field=models.CharField(max_length=10),
        ),
    ]
